# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sarraounia Prize
collections:
  posts:
    title: Posts
    output: true
  testimonials:
    title: testimonials
    output: true
  schedules:
    title: schedules
    output: true
  partners:
    title: partners
    output: true
  jury_members:
    title: jury_members
    output: true
lang: nu
email: contact@sarraounia.com
parallax_image: "/uploads/africa_5.jpg"
image: "/uploads/SarraouniaPrize_LogoEnglish_Color.png"
description: >- # this means to ignore newlines until "baseurl:"
  The Arts & Culture programme at Abdou Moumouni University in Niger and the publishing
  house Amalion in Senegal are pleased to announce the call for entries for the Sarraounia
  Prize for Young Adult Fiction, co-funded by the European Union and Culture at Work Africa
  to contribute to the availability of reading material for African young adults and to 
  promote literature to help better understand the world of African youths.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
